### ISSUE TITLE
panic: runtime error while trying to download some chapters

### ISSUE THREAD

**Issue by oae** [metafates/mangal#135]
### Describe the bug

This does not occur frequently but sometimes mangal throws an error during a chapter download.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5037e2]

goroutine 1 [running]:
bytes.(*Buffer).WriteTo(0x153e720?, {0x153e720?, 0xc0002fa460?})
	bytes/buffer.go:250 +0x22
io.copyBuffer({0x153e720, 0xc0002fa460}, {0x153e7c0, 0x0}, {0x0, 0x0, 0x0})
	io/io.go:409 +0x16e
io.Copy(...)
	io/io.go:386
github.com/metafates/mangal/converter/cbz.addToZip(0xc0004009c0?, {0x153e7c0, 0x0}, {0xc0000bd0e0, 0xa})
	github.com/metafates/mangal/converter/cbz/cbz.go:83 +0xa6
github.com/metafates/mangal/converter/cbz.SaveTo(0xc000348600, {0xc0000459b0?, 0xc000b55828?})
	github.com/metafates/mangal/converter/cbz/cbz.go:55 +0x36b
github.com/metafates/mangal/converter/cbz.save(0xe5bd20?, 0x60?)
	github.com/metafates/mangal/converter/cbz/cbz.go:35 +0x3f
github.com/metafates/mangal/converter/cbz.(*CBZ).Save(0xc000116900, 0x4?)
	github.com/metafates/mangal/converter/cbz/cbz.go:22 +0x1e
github.com/metafates/mangal/downloader.Download(0xc000348600, 0x12da8f0)
	github.com/metafates/mangal/downloader/download.go:104 +0xbe7
github.com/metafates/mangal/inline.Run(0xc000b55c88)
	github.com/metafates/mangal/inline/inline.go:121 +0x5dd
github.com/metafates/mangal/cmd.glob..func11(0x1cf7b60?, {0x1006797?, 0x9?, 0x9?})
	github.com/metafates/mangal/cmd/inline.go:149 +0x567
github.com/spf13/cobra.(*Command).execute(0x1cf7b60, {0xc000128900, 0x9, 0x9})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1cfaf20)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/metafates/mangal/cmd.Execute()
	github.com/metafates/mangal/cmd/root.go:109 +0x5e
main.main()

```

### Reproduction steps

The following commands are failing;

-  `mangal inline --source Manganelo --query "Black Clover" --manga first --chapters 347 -d`
- ` mangal inline --source Manganelo --query "Black Clover" --manga first --chapters 348 -d`

### Operating System

Linux

**Comment by metafates** [comment]
Hi! Thanks for reporting.

I'll take a look on it asap, but currently I'm very busy 😵‍💫

**Comment by leycec** [comment]
**Gah!** I just stumbled forehead-first into this, too. The traceback is *slightly* different, but ultimately just the same low-level buffering thing (i.e., busted usage of `io.Copy()` somehow):

```go
panic: runtime error: invalid memory address or nil pointer dereference                                                        
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x505502]

goroutine 87 [running]:
bytes.(*Buffer).WriteTo(0x4e?, {0x1547220?, 0xc000014d20?})
	/usr/lib/go/src/bytes/buffer.go:250 +0x22
io.copyBuffer({0x1547220, 0xc000014d20}, {0x1545580, 0x0}, {0x0, 0x0, 0x0})
	/usr/lib/go/src/io/io.go:409 +0x16e
io.Copy(...)
	/usr/lib/go/src/io/io.go:386
github.com/metafates/mangal/converter/plain.savePage(0xc00033c900, {0xc00007e5a0, 0x43})
	/var/tmp/portage/app-misc/mangal-4.0.4/work/mangal-4.0.4/converter/plain/plain.go:61 +0xf1
github.com/metafates/mangal/converter/plain.save.func1(0xc0002dc580?, 0xc00055dc50, 0xc00026e90b?, 0x7f6f9e71a718?)
	/var/tmp/portage/app-misc/mangal-4.0.4/work/mangal-4.0.4/converter/plain/plain.go:47 +0x69
github.com/metafates/mangal/converter/plain.save(0xc0002dc580, 0x1?)
	/var/tmp/portage/app-misc/mangal-4.0.4/work/mangal-4.0.4/converter/plain/plain.go:48 +0x10c
github.com/metafates/mangal/converter/plain.(*Plain).Save(0xc00026e900, 0x10?)
	/var/tmp/portage/app-misc/mangal-4.0.4/work/mangal-4.0.4/converter/plain/plain.go:19 +0x1e
github.com/metafates/mangal/downloader.Download(0xc0002dc580, 0xc0002d6c70)
	/var/tmp/portage/app-misc/mangal-4.0.4/work/mangal-4.0.4/downloader/download.go:104 +0xbe7
github.com/metafates/mangal/tui.(*statefulBubble).downloadChapter.func1()
	/var/tmp/portage/app-misc/mangal-4.0.4/work/mangal-4.0.4/tui/handlers.go:250 +0x98
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func6.1()
	/var/tmp/portage/app-misc/mangal-4.0.4/work/mangal-4.0.4/vendor/github.com/charmbracelet/bubbletea/tea.go:469 +0x33
created by github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func6
	/var/tmp/portage/app-misc/mangal-4.0.4/work/mangal-4.0.4/vendor/github.com/charmbracelet/bubbletea/tea.go:467 +0x14d
```

Thanks so much for all the manga madness, @metafates! I cannot believe you're "just" a CompSci undergrad. `mangal` is God-tier coding. I would pay you in anime waifu statues to maintain this magnificence if I could. :grin:

**Comment by metafates** [comment]
@leycec haha, thank you for the kind words! I believe the problem isn't that complex, but yeah, I'm still crazy busy because of finals preparation in the university, so didn't really had a chance to get a look on the problem 😞

**Comment by leycec** [comment]
:clap: :partying_face: :christmas_tree: :santa: :christmas_tree: :partying_face: :clap:

**Comment by oae** [comment]
@metafates it seems like this problem continues. For the chapter below, its Page 95 image returns 404 and after that, the following error is thrown. Also, this creates a [cbz file](https://filebin.net/pbdu60l0oj1i6sfl) that is not complete. By the way `downloader.stop_on_error` config is set to `true`. So I think it should not create a cbz file.

```bash
➜  mangal inline --source Manganelo --query Subzero --manga first --chapters 141 -d
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5055c2]

goroutine 1 [running]:
bytes.(*Buffer).WriteTo(0x1560b20?, {0x1560b20?, 0xc00013f400?})
	bytes/buffer.go:250 +0x22
io.copyBuffer({0x1560b20, 0xc00013f400}, {0x1560bc0, 0x0}, {0x0, 0x0, 0x0})
	io/io.go:409 +0x16e
io.Copy(...)
	io/io.go:386
github.com/metafates/mangal/converter/cbz.addToZip(0xc0000c99c0?, {0x1560bc0, 0x0}, {0xc0017a2f40, 0xa})
	github.com/metafates/mangal/converter/cbz/cbz.go:83 +0xa6
github.com/metafates/mangal/converter/cbz.SaveTo(0xc000197000, {0xc00187fdd0?, 0xc000963838?})
	github.com/metafates/mangal/converter/cbz/cbz.go:55 +0x36b
github.com/metafates/mangal/converter/cbz.save(0xe70420?, 0x0?)
	github.com/metafates/mangal/converter/cbz/cbz.go:35 +0x3f
github.com/metafates/mangal/converter/cbz.(*CBZ).Save(0xc00012a180, 0x4?)
	github.com/metafates/mangal/converter/cbz/cbz.go:22 +0x1e
github.com/metafates/mangal/downloader.Download(0xc000197000, 0x12f1ec0)
	github.com/metafates/mangal/downloader/download.go:104 +0xbe7
github.com/metafates/mangal/inline.Run(0xc000963c88)
	github.com/metafates/mangal/inline/inline.go:121 +0x5dd
github.com/metafates/mangal/cmd.glob..func11(0x1d26c80?, {0x101d881?, 0x9?, 0x9?})
	github.com/metafates/mangal/cmd/inline.go:149 +0x567
github.com/spf13/cobra.(*Command).execute(0x1d26c80, {0xc000592090, 0x9, 0x9})
	github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1d2a040)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/metafates/mangal/cmd.Execute()
	github.com/metafates/mangal/cmd/root.go:112 +0x7a
main.main()
	github.com/metafates/mangal/main.go:13 +0x4d
```

JSON output for `mangal inline --source Manganelo --query Subzero --manga first --chapters 141 --populate-pages -j`:

```json
{
  "query": "Subzero",
  "result": [
    {
      "source": "Manganelo",
      "mangal": {
        "name": "Subzero",
        "url": "https://ww5.manganelo.tv/manga/manga-gr983774",
        "index": 0,
        "id": "manga-gr983774",
        "chapters": [
          {
            "name": "Chapter 137",
            "url": "https://ww5.manganelo.tv/chapter/manga-gr983774/chapter-137",
            "index": 142,
            "id": "chapter-137",
            "volume": "",
            "pages": [
              {
                "url": "https://cm.blazefast.co/eb/c2/ebc26fadca663fd6a0c9a6544ba91a01.jpg",
                "index": 0,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/07/2f/072fe4d4d4418b0c885422f45585ac46.jpg",
                "index": 1,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/ae/75/ae758f577f95ebd00e492b63eb526d9b.jpg",
                "index": 2,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/b0/cf/b0cf22381ee9b97e324fd439f51838f2.jpg",
                "index": 3,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/7f/57/7f57ac098c97fb3f0456744f679bff4c.jpg",
                "index": 4,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/97/86/9786f831dd8d276644ab09c12a1a050a.jpg",
                "index": 5,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/96/45/964503ad8a95795047e2155aa76e7600.jpg",
                "index": 6,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/75/ba/75ba9c14ab4cc464e3b4252d42724971.jpg",
                "index": 7,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/9a/9f/9a9fd61e0fe83df7702299ea105ebf43.jpg",
                "index": 8,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/bd/c5/bdc512cabc0bde7ef6f94db254fbd271.jpg",
                "index": 9,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/d5/46/d546054721b2b1559b493ad7af6feaf7.jpg",
                "index": 10,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/db/c3/dbc3e000b954511fbe3320497bbbe086.jpg",
                "index": 11,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/b9/b0/b9b0e2c234114aefa538b61dc6462ae1.jpg",
                "index": 12,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/78/4b/784b2b91e4fe80a65a3adf61f5fc9455.jpg",
                "index": 13,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/62/e8/62e80f149a7f8faa967a9b1594b8f602.jpg",
                "index": 14,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/5b/da/5bdad54aa34ebda5be8d23c29e2a9768.jpg",
                "index": 15,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/90/3c/903c8355a274e519e571f21261b99dd7.jpg",
                "index": 16,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/10/57/1057dba9331f0ed7dace96f3d9b7923f.jpg",
                "index": 17,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/21/e5/21e54f9f0185ddd4ccdec033a859ae23.jpg",
                "index": 18,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/d1/fa/d1faf5f6f9151ca52a7d09ce66b40b66.jpg",
                "index": 19,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/95/84/9584b33467dda4bae2883fb35f94eb27.jpg",
                "index": 20,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/be/6d/be6d8e9d3a1d2c5b3f10a7baf018dcd6.jpg",
                "index": 21,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/6f/1b/6f1bfb3bbc18024f80f62e514a24391b.jpg",
                "index": 22,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/fd/e5/fde5111c4c6cd21996ae61b46243d4e2.jpg",
                "index": 23,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/3b/cb/3bcb6dec6521396750499b1278c4a77a.jpg",
                "index": 24,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/0d/d6/0dd60891328fa9ff183d0b7be59ea9d4.jpg",
                "index": 25,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/6f/ce/6fcefc2b8678584cdd14200ce73c8693.jpg",
                "index": 26,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/b0/d6/b0d6b07193284db3055feda411114d63.jpg",
                "index": 27,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/be/b4/beb4a0d7db3a29274c520dbc420d8272.jpg",
                "index": 28,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/ae/e3/aee3c8c9e7f6f97e81ec46a57062fca4.jpg",
                "index": 29,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/5e/87/5e87bc3e682249e4820de0f932737f3c.jpg",
                "index": 30,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/b0/8f/b08fd4d17639fd70fe05afea4e7f99ec.jpg",
                "index": 31,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/53/81/53812b95be9c58f20323b53fb0e39fd3.jpg",
                "index": 32,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/12/83/12835842b8dd013b215d835cbcf6a459.jpg",
                "index": 33,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/ee/85/ee855a29ef4880ce9e15169843caed24.jpg",
                "index": 34,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/98/ad/98ad06855e36cbaf6331700dfb670c3a.jpg",
                "index": 35,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/98/56/985635409dee8061a5bdc8458df22a35.jpg",
                "index": 36,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/c1/87/c18750c207c2aa0718a45b94a21ca232.jpg",
                "index": 37,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/6b/f6/6bf6b47d05ff8ffef00f71cbb0700887.jpg",
                "index": 38,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/50/d1/50d11b2b9f5c94e536506e7d2479b66d.jpg",
                "index": 39,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/02/2a/022a260d800c214ea596254b499f26b9.jpg",
                "index": 40,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/83/a2/83a211f3e0040dddc531fcbd1035c2ff.jpg",
                "index": 41,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/9a/2b/9a2b3b2ac7634cc9a871c24ce331aea3.jpg",
                "index": 42,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/81/ca/81cab4e0698701e9803e0827e5cbe824.jpg",
                "index": 43,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/d1/da/d1dac2db21c549ec3fec2047c125b102.jpg",
                "index": 44,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/01/60/0160c891614c0ea8e72b0770b2513eb5.jpg",
                "index": 45,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/e7/c0/e7c06f880b09a55e63e9d096634e4a6e.jpg",
                "index": 46,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/1a/08/1a08bc07e252056ce40a9ad85c3d8f20.jpg",
                "index": 47,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/42/f3/42f3b99dfe244299c9a0265c59c5048d.jpg",
                "index": 48,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/c3/46/c346f1a602ce549418261fc3435d96f6.jpg",
                "index": 49,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/f3/f8/f3f86194bbf5f5d7d94ad74b256e1197.jpg",
                "index": 50,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/a9/ee/a9ee89ad626c2803adb38dcc18189f6b.jpg",
                "index": 51,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/6b/9e/6b9e97dc5adaf0f86a759ff71a977f05.jpg",
                "index": 52,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/e4/df/e4df523c6aea5d91eb5b40488ebe73b6.jpg",
                "index": 53,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/d5/40/d54069aeb2ab4603728f8ba222b0f658.jpg",
                "index": 54,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/b3/6f/b36fb0a373ffd61125e96822c05c8d1d.jpg",
                "index": 55,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/87/a0/87a0fa8d8ec323be647c51087a934c2c.jpg",
                "index": 56,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/0c/2b/0c2bdf0142da9ba29649dc899ddb0746.jpg",
                "index": 57,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/70/d0/70d0361adbf8f18927f11ccf714bace9.jpg",
                "index": 58,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/95/17/951761bb6d4ebc42974c1a5f3988b053.jpg",
                "index": 59,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/2f/a2/2fa2453f008ac7d25107ea9a7992ae8c.jpg",
                "index": 60,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/ad/29/ad295c22bcdaa7cf8ab21ef901b70b30.jpg",
                "index": 61,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/98/07/9807d4a23360908ba97a17b3889442e3.jpg",
                "index": 62,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/7c/f7/7cf7fe9ca5656b75c976ea035fe738e9.jpg",
                "index": 63,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/46/1c/461c0a91188904e5aff161e2960624b2.jpg",
                "index": 64,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/29/17/2917eefc612d28536f0da13de3182c54.jpg",
                "index": 65,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/ac/dd/acdda2053fdac1d7dad59a30ed30ae5a.jpg",
                "index": 66,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/04/ca/04ca86d2e6b4a28b4563f6e16f90a7ea.jpg",
                "index": 67,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/90/a8/90a858945e3c55484f1b9a4f804564f2.jpg",
                "index": 68,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/d7/e5/d7e5f445ac72e96a139de79bd191e571.jpg",
                "index": 69,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/9b/a5/9ba56f2063efb4433f121cc204a02b1c.jpg",
                "index": 70,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/fb/ca/fbca8f21a086be440b7c3cfca0064e54.jpg",
                "index": 71,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/6f/09/6f09eb55c0dac487950acd4e0c36dd84.jpg",
                "index": 72,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/63/d3/63d37bbe0f05021fe2117edba2c191dc.jpg",
                "index": 73,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/f0/37/f0370229fbcbb585b3023feb0cf3d318.jpg",
                "index": 74,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/8e/dd/8edd0bdaaca31cb669fdc01990c01e95.jpg",
                "index": 75,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/d2/97/d297e678deeb4f0ee35b4990936fd46a.jpg",
                "index": 76,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/61/0c/610c544ee67c4769d01b73257888f535.jpg",
                "index": 77,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/84/1d/841d6a7be4b9d6a035d6dd6fcf7e44c1.jpg",
                "index": 78,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/fc/c3/fcc3911e7ea28d001208be142bc82cc4.jpg",
                "index": 79,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/7d/b1/7db14b7283a831a3dab541e06d3edeb0.jpg",
                "index": 80,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/d5/8a/d58ad53609ffc30056c15bfaa589e213.jpg",
                "index": 81,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/31/b6/31b66950f73240ba3c2c4a9efdaf74f6.jpg",
                "index": 82,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/9e/6d/9e6d68f521d7c71e3e8e3d8e52f85bda.jpg",
                "index": 83,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/77/d1/77d147d8ebf5e61a0d1a1f49ef0a155b.jpg",
                "index": 84,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/17/61/1761a29af3b4badc12740d85caf6c148.jpg",
                "index": 85,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/26/96/2696f5eb660391421c302cce1f773808.jpg",
                "index": 86,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/46/7a/467a86643f5bfe99ed2b0d000a920cef.jpg",
                "index": 87,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/08/95/08954aafa51e22706473d336da1106c5.jpg",
                "index": 88,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/02/ea/02eae5179babfae0ddeff00200d41029.jpg",
                "index": 89,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/60/00/60002a1e36841cb72ad04ac9db64068f.jpg",
                "index": 90,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/50/b6/50b6efb8275b797ce6a813ed8587c388.jpg",
                "index": 91,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/a8/91/a8918a810814c5f30f4b5fc16c2694c5.jpg",
                "index": 92,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/d0/e5/d0e543b059fdc04495a77dfd2295ba32.jpg",
                "index": 93,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/2a/88/2a88fb54493029471b28c411da0bb645.jpg",
                "index": 94,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/3a/71/3a71272b4be00188fb9eb23847d8f341.jpg",
                "index": 95,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/1d/0d/1d0d9713573061436858a6a520edfe51.jpg",
                "index": 96,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/e1/b7/e1b794f16c19c8d27a2ab5b41cdf2369.jpg",
                "index": 97,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/ae/90/ae909b00071c8d46cffffeab1daa22b4.jpg",
                "index": 98,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/a3/f3/a3f33cd3af1293d8015aedb4195416ae.jpg",
                "index": 99,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/f0/4a/f04a224417caa18040715876ad1b03ee.jpg",
                "index": 100,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/b6/9e/b69ef303925819006e19dd771402c9e6.jpg",
                "index": 101,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/11/4c/114c3697d1425a6c3537db7923cbc063.jpg",
                "index": 102,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/28/ec/28ec59354f7dd54228cb2a86f836004b.jpg",
                "index": 103,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/f7/03/f703f3a8918d01ab1b47ab675f1f9016.jpg",
                "index": 104,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/35/70/35701f9fbc1c25482d9a95742fa680b2.jpg",
                "index": 105,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/09/2c/092c23bc2a417eb209c520268173d29a.jpg",
                "index": 106,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/cd/26/cd26778f5cb312f81038a0ad5bb8eb98.jpg",
                "index": 107,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/50/3f/503f3d7bd046e4e65d1a3231075c8021.jpg",
                "index": 108,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/72/42/7242400e2cad8f321489e4b05c7c2af6.jpg",
                "index": 109,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/f0/98/f09894a9f868978f3822001baaca4073.jpg",
                "index": 110,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/68/f3/68f397c7723ec858993b30a65278e1f6.jpg",
                "index": 111,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/d4/e0/d4e0908a8dbb730e294a40ce90fea5a4.jpg",
                "index": 112,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/bf/a5/bfa509f8a56007774f668abc25de5728.jpg",
                "index": 113,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/6a/6d/6a6ddce90fef04cadaff8b3c6dfe9e5e.jpg",
                "index": 114,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/6d/d9/6dd96e2634aaf50d148c0e9267c4f9ee.jpg",
                "index": 115,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/68/88/68888b3423a537cf0e4e6922a19fe319.jpg",
                "index": 116,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/03/2c/032ca002a798c73d6b1d106a7ac64f60.jpg",
                "index": 117,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/6d/d5/6dd5f1388348d0f4f362d95846c35caa.jpg",
                "index": 118,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/6b/ca/6bcaf8c9a9f90b42821c480594f0e9b9.jpg",
                "index": 119,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/eb/64/eb64600df103db5078f4aebca11f640f.jpg",
                "index": 120,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/1c/5f/1c5feac068300a501b6d9cb9b13e1bc0.jpg",
                "index": 121,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/40/8e/408e40f1f36bc98cd4d17bdd5df636a5.jpg",
                "index": 122,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/09/7a/097ad3bba26a9713c8ef2462f9e2e528.jpg",
                "index": 123,
                "extension": ".jpg"
              },
              {
                "url": "https://cm.blazefast.co/d4/1a/d41ae5c3facf8e87f79ff3c701802a71.jpg",
                "index": 124,
                "extension": ".jpg"
              }
            ]
          }
        ],
        "metadata": {
          "genres": [
            "Action",
            "Sci-Fi"
          ],
          "summary": "On January 3rd, 2097, a collision with a celestial object basically destroyed human civilization. Seventy years later, human survivors are still living in space, unable to return to their home planet. Some humans, called \"Divers\" are able to project an avatar to the earth in order to salvage information from earth-based computer networks.\n\n\nSuzuro is a 14-year-old freelance diver of incredible skill, but only a C-rank due to age restrictions. She works in a salvage ship with her pilot Ginga, who keeps the ship out of flying debris while she's connected to earth, and her assistant Shimugi. It's not only space debris colliding with the ship that could kill Suzuro while diving, there are also dangers waiting on earth that could kill her, just by interacting with her avatar. Suzuro must be certain that the cases she takes are worth the danger!\n",
          "staff": {
            "story": [
              "FLIPFLOPs"
            ],
            "art": [],
            "translation": [],
            "lettering": []
          },
          "cover": {
            "extraLarge": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/18840.jpg",
            "large": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/medium/18840.jpg",
            "medium": "https://s4.anilist.co/file/anilistcdn/media/manga/cover/small/18840.jpg",
            "color": "#e4bba1"
          },
          "bannerImage": "",
          "tags": [],
          "characters": [],
          "status": "FINISHED",
          "startDate": {
            "year": 2010,
            "month": 1,
            "day": 19
          },
          "endDate": {
            "year": 2012,
            "month": 11,
            "day": 19
          },
          "synonyms": [
            "Suzu Log",
            "Suzuro's Log",
            "Suzuro's Logfile"
          ],
          "chapters": 0,
          "urls": [
            "https://anilist.co/manga/48840",
            "https://myanimelist.net/manga/18840"
          ]
        }
      },
      "anilist": null
    }
  ]
}
```
