### ISSUE TITLE
Mangadex download bug (delimiter)

### ISSUE THREAD

**Issue by C9Glax** [metafates/mangal#150]
### Describe the bug

`runtime error: index out of range [99] with length 99`
The index is always the length. Only occurs with Mangadex
Titles with occurrences (also some weird ones) and index:
- A Returner's Magic Should Be Special [26]
- Kaifuku Jutsushi no Yarinaoshi [99]
- Kumo Desu ga, Nani ka? [91]
- Kanojo, Okarishimasu [99]
- Monster no Goshujin-sama [84]
- Ijiranaide, Nagatoro-san [95]
- Overlord [79]

Also one full line:
```
{"level":50,
"time":1675028575839,
"pid":307,
"hostname":"fecb3815dfa6",
"msg":
  "Failed to download the chapter #110 for Ijiranaide, Nagatoro-san. Err:
  Error: Command failed with exit code 2: mangal inline --source Mangadex --query Ijiranaide, Nagatoro-san --manga exact --chapters 110 -d
  panic: runtime error: index out of range [95] with length 95

  goroutine 1 [running]:
  github.com/metafates/mangal/inline.ParseChaptersFilter.func1({0xc000276480?, 0x5f, 0x8d})
    github.com/metafates/mangal/inline/options.go:114 +0x378
  github.com/metafates/mangal/inline.Run(0xc000567c88)
    github.com/metafates/mangal/inline/inline.go:99 +0x474
  github.com/metafates/mangal/cmd.glob..func11(0x1d26c80?, {0x101d881?, 0x9?, 0x9?})
    github.com/metafates/mangal/cmd/inline.go:149 +0x567
  github.com/spf13/cobra.(*Command).execute(0x1d26c80, {0xc0002307e0, 0x9, 0x9})
    github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
  github.com/spf13/cobra.(*Command).ExecuteC(0x1d2a040)
    github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
  github.com/spf13/cobra.(*Command).Execute(...)
    github.com/spf13/cobra@v1.6.1/command.go:968
  github.com/metafates/mangal/cmd.Execute()
    github.com/metafates/mangal/cmd/root.go:112 +0x7a
  main.main()
    github.com/metafates/mangal/main.go:13 +0x4d"
}
```

### Additional context

Docker container

### Operating System

Linux

**Comment by timbroder** [comment]
Adding a few more samples

* Dragon Ball Super[35] chapter 134
* Ranma_1_2[236] ch339

**Comment by C9Glax** [comment]
Okay I have no idea on what is actually happening, because I only read this one function, but what I think is the error:
https://github.com/metafates/mangal/blob/main/inline/options.go
Line 110:
`from = util.Min(from, uint64(len(chapters)))` should actually subtract 1 ?
Just a shot in the dark really...

**Comment by metafates** [comment]
> https://github.com/metafates/mangal/blob/main/inline/options.go
> 
> Line 110:
> 
> `from = util.Min(from, uint64(len(chapters)))` should actually subtract 1 ?

Actually, that might be the case, lol

**Comment by Ellwindrae** [comment]
Wanted to add a few more samples:
Helck_chapter#405
Helck_chapter#395
Helck_chapter#440
[Oshi_no_Ko]_chapter#142
[Oshi_no_Ko]_chapter#238

Have a decent number more if there is a way to export my Bull Dashboard.
